/** Literal mirrors of Core v0.12.0 sessionwire/v1, checked against contract/schema. */
import type { JSONSchema as JSONSchemaToTS } from "json-schema-to-ts";

/** json-schema-to-ts's draft-07 surface omits draft-2020-12 `$defs`. */
type JSONSchema = JSONSchemaToTS & { readonly $defs?: Readonly<Record<string, unknown>> };

export const factoryAgentCapabilitySummarySchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/agent_capability_summary.schema.json","title":"AgentCapabilitySummary","description":"Forward-compatible public capability summary without launch internals.","type":"object","additionalProperties":true,"required":["agent_id","runtime_compatibility_id"],"properties":{"agent_id":{"$ref":"#/$defs/id"},"runtime_compatibility_id":{"$ref":"#/$defs/id"},"capabilities":{"type":"array","items":{"type":"string"}}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."}}} as const satisfies JSONSchema;

export const factoryDepartmentCapabilitySummarySchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/department_capability_summary.schema.json","title":"DepartmentCapabilitySummary","description":"Forward-compatible public Department capability discovery response.","type":"object","additionalProperties":true,"required":["agents"],"properties":{"agents":{"type":"array","items":{"$ref":"#/$defs/agent"}}},"$defs":{"agent":{"type":"object","additionalProperties":true,"required":["agent_id","runtime_compatibility_id"],"properties":{"agent_id":{"type":"string","minLength":1},"runtime_compatibility_id":{"type":"string","minLength":1},"capabilities":{"type":"array","items":{"type":"string"}}}}}} as const satisfies JSONSchema;

export const factoryRecentSessionPageSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/recent_session_page.schema.json","title":"SessionPage","description":"Bounded recent-first durable page. The Core decoder verifies non-increasing last_active_at order.","type":"object","additionalProperties":true,"required":["sessions"],"properties":{"sessions":{"type":"array","items":{"$ref":"#/$defs/session"}},"next_cursor":{"type":"string"},"previous_cursor":{"type":"string"}},"$defs":{"session":{"type":"object","additionalProperties":true,"required":["session_id","agent_id","state","last_active_at"],"properties":{"session_id":{"type":"string","minLength":1},"agent_id":{"type":"string","minLength":1},"state":{"type":"string","minLength":1},"title":{"type":"string"},"created_at":{"type":"string","format":"date-time"},"last_active_at":{"type":"string","format":"date-time"}}}}} as const satisfies JSONSchema;

export const factorySessionStatusSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/session_status.schema.json","title":"SessionStatus","description":"Forward-compatible durable session state and residency projection.","type":"object","additionalProperties":true,"required":["session_id","agent_id","state","residency","journal_tip"],"properties":{"session_id":{"$ref":"#/$defs/id"},"agent_id":{"$ref":"#/$defs/id"},"state":{"type":"string","minLength":1},"residency":{"type":"string","minLength":1},"journal_tip":{"type":"integer","minimum":0},"waiting_gate_id":{"$ref":"#/$defs/id"},"updated_at":{"type":"string","format":"date-time"}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."}}} as const satisfies JSONSchema;

export const factoryPublicJournalPageSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/public_journal_page.schema.json","title":"JournalPage","description":"Bounded public journal page. covered_through can bridge private records without exposing their kind or bytes.","type":"object","additionalProperties":true,"required":["events","journal_tip","covered_through"],"properties":{"events":{"type":"array","items":{"$ref":"#/$defs/event"}},"journal_tip":{"type":"integer","minimum":0},"covered_through":{"type":"integer","minimum":0},"next_cursor":{"type":"string"},"previous_cursor":{"type":"string"}},"$defs":{"event":{"type":"object","additionalProperties":true,"required":["event_id","journal_seq","body"],"properties":{"event_id":{"type":"string","minLength":1},"journal_seq":{"type":"integer","minimum":1},"body":{"not":{"type":"null"}}}}}} as const satisfies JSONSchema;

export const factoryPublicGatePageSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/public_gate_page.schema.json","title":"GatePage","description":"Bounded public page of open gates captured at journal_tip. Prompts are presentation-safe projections only.","type":"object","additionalProperties":true,"required":["journal_tip","open_gate_count","gates"],"properties":{"journal_tip":{"type":"integer","minimum":0},"open_gate_count":{"type":"integer","minimum":0},"gates":{"type":"array","items":{"$ref":"#/$defs/gate"}},"next_cursor":{"type":"string"},"previous_cursor":{"type":"string"}},"$defs":{"gate":{"type":"object","additionalProperties":true,"required":["gate_id","kind","prompt","opened_event_id","opened_journal_seq","deadline","answerability"],"properties":{"gate_id":{"type":"string","minLength":1},"kind":{"type":"string","minLength":1},"prompt":{"$ref":"#/$defs/prompt"},"opened_event_id":{"type":"string","minLength":1},"opened_journal_seq":{"type":"integer","minimum":1},"deadline":{"type":"string","format":"date-time"},"answerability":{"enum":["resident","suspended","submitted","unavailable","expired"]}}},"prompt":{"type":"object","additionalProperties":true,"properties":{"title":{"type":"string"},"body":{"type":"string"},"origin":{"type":"string","format":"uri"},"schema":{"$ref":"#/$defs/prompt_schema"},"controls":{"type":"array","items":{"type":"object","additionalProperties":true,"required":["action","label"],"properties":{"action":{"type":"string","minLength":1},"label":{"type":"string","minLength":1}}}}}},"prompt_schema":{"type":"object","additionalProperties":true,"properties":{"fields":{"type":"array","items":{"type":"object","additionalProperties":true,"required":["name","label","kind","required"],"properties":{"name":{"type":"string","minLength":1},"label":{"type":"string"},"kind":{"enum":["text","select","multi_select","confirm"]},"required":{"type":"boolean"},"options":{"type":"array"},"default":{}}}}}}}} as const satisfies JSONSchema;

export const factoryObjectMetadataSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/object_metadata.schema.json","title":"ObjectMetadata","description":"Strict redaction boundary for immutable logical object metadata. Signed URLs, secret material, backend paths, and object bytes are not part of this contract.","type":"object","additionalProperties":false,"required":["reference","size_bytes"],"properties":{"reference":{"type":"object","additionalProperties":false,"required":["object_id"],"properties":{"object_id":{"type":"string","minLength":1}}},"size_bytes":{"type":"integer","minimum":0},"media_type":{"type":"string"},"digest":{"type":"string"},"created_at":{"type":"string","format":"date-time"}}} as const satisfies JSONSchema;

export const factoryEnduringPublicationSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/enduring_publication.schema.json","title":"EnduringPublication","description":"Forward-compatible live relay of one committed public journal event. Core enforces journal_seq == covered_through and the raw body fixed-point JSON representation.","type":"object","additionalProperties":true,"required":["type","tenant_id","session_id","event_id","journal_seq","covered_through","body"],"properties":{"type":{"const":"enduring_publication","type":"string","description":"Stable session-channel record name. Every record published on session:{tid}:{sid} names its own kind here."},"tenant_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"event_id":{"$ref":"#/$defs/id"},"journal_seq":{"type":"integer","minimum":1},"covered_through":{"type":"integer","minimum":1},"body":{"not":{"type":"null"}}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."}}} as const satisfies JSONSchema;

export const factoryEphemeralPublicationSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/ephemeral_publication.schema.json","title":"EphemeralPublication","description":"Forward-compatible best-effort public delta. It intentionally has no event_id, journal_seq, or covered_through durable promise; Core rejects those members on decode.","type":"object","additionalProperties":true,"required":["type","tenant_id","session_id","body"],"properties":{"type":{"const":"ephemeral_publication","type":"string","description":"Stable session-channel record name. Every record published on session:{tid}:{sid} names its own kind here."},"tenant_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"body":{"not":{"type":"null"}}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."}}} as const satisfies JSONSchema;

export const factoryJournalTipSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/journal_tip.schema.json","title":"JournalTip","description":"Forward-compatible repeatable durable-repair hint, not a client acknowledgement or cursor.","type":"object","additionalProperties":true,"required":["type","tenant_id","session_id","journal_tip"],"properties":{"type":{"const":"journal_tip","type":"string","description":"Stable session-channel record name. Every record published on session:{tid}:{sid} names its own kind here."},"tenant_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"journal_tip":{"type":"integer","minimum":0}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."}}} as const satisfies JSONSchema;

export const factorySessionResetSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/session_reset.schema.json","title":"SessionReset","description":"Forward-compatible repair control after a durable live-tail gap. Core enforces last_contiguous <= journal_tip.","type":"object","additionalProperties":true,"required":["type","tenant_id","session_id","last_contiguous","journal_tip"],"properties":{"type":{"const":"session.reset","type":"string","description":"Stable session-channel record name. Every record published on session:{tid}:{sid} names its own kind here."},"tenant_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"last_contiguous":{"type":"integer","minimum":0},"journal_tip":{"type":"integer","minimum":0}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."}}} as const satisfies JSONSchema;

export const factoryVersionNegotiationRequestSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/version_negotiation_request.schema.json","title":"VersionNegotiationRequest","description":"Strict pre-control offer of nonzero, duplicate-free sessionwire versions.","type":"object","additionalProperties":false,"required":["supported_versions"],"properties":{"supported_versions":{"type":"array","minItems":1,"uniqueItems":true,"items":{"type":"integer","minimum":1}}}} as const satisfies JSONSchema;

export const factoryVersionNegotiationResponseSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/version_negotiation_response.schema.json","title":"VersionNegotiationResponse","description":"Forward-compatible selected sessionwire version. hostlink_methods is the optional set of reserved HostLink method names the replying Host serves; it is absent when the Host advertises nothing and its item values are deliberately open so a method added later does not invalidate an older consumer.","type":"object","additionalProperties":true,"required":["version"],"properties":{"version":{"const":1},"hostlink_methods":{"type":"array","uniqueItems":true,"items":{"type":"string","minLength":1,"description":"A reserved HostLink method name such as hostlink.attach; Core enforces the 256-byte identifier limit and tolerates a name it does not know."}}}} as const satisfies JSONSchema;

export const factoryCommandStatusSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/command_status.schema.json","title":"CommandStatus","description":"Forward-compatible durable command lifecycle response. A rejected command has a stable public error detail.","type":"object","additionalProperties":true,"required":["command_id","status"],"properties":{"command_id":{"$ref":"#/$defs/id"},"status":{"enum":["accepted","pending","applied","rejected"]},"accepted_order":{"type":"integer","minimum":1},"error":{"$ref":"#/$defs/error"}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."},"error":{"type":"object","additionalProperties":true,"required":["code","retryable"],"properties":{"code":{"type":"string","minLength":1},"message":{"type":"string"},"retryable":{"type":"boolean"}}}}} as const satisfies JSONSchema;

export const factoryErrorEnvelopeSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/error_envelope.schema.json","title":"ErrorEnvelope","description":"Forward-compatible public error envelope. Error codes are stable while messages remain safe presentation text.","type":"object","additionalProperties":true,"required":["error"],"properties":{"error":{"type":"object","additionalProperties":true,"required":["code","retryable"],"properties":{"code":{"type":"string","minLength":1},"message":{"type":"string"},"retryable":{"type":"boolean"}}}}} as const satisfies JSONSchema;

/** Core v0.12.0 command request and sender schemas, generated from the vendored JSON by the plan's node command. */
export const factoryCreateRequestSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/create_request.schema.json","title":"CreateRequest","description":"Retry-safe durable create command. session_id and command_id are client-generated opaque V1 identities. metadata is optional client-supplied app-defined fields; principal is optional and only ever Factory-stamped.","type":"object","additionalProperties":false,"required":["version","command_id","session_id","agent_id"],"properties":{"version":{"const":1},"command_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"agent_id":{"$ref":"#/$defs/id"},"blocks":{"type":"array","minItems":1,"items":{"type":"object"}},"metadata":{"$ref":"#/$defs/metadata"},"principal":{"$ref":"#/$defs/principal"}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."},"metadata":{"type":"object","description":"Client-supplied app-defined string fields. Core also enforces: 1 to 16 fields; keys match ^[a-z][a-z0-9_]{0,63}$ and do not begin with looprig; values are at most 1024 bytes of UTF-8 with no C0 control other than tab and newline; the canonical encoding of the object is at most 4096 bytes.","not":{"const":{}},"additionalProperties":{"type":"string"}},"principal":{"type":"object","description":"The verified sender a Factory stamped after credential verification. Never client-supplied: a Factory refuses a request that carries it.","additionalProperties":false,"required":["tenant","subject","kind"],"properties":{"tenant":{"$ref":"#/$defs/id"},"subject":{"$ref":"#/$defs/id"},"kind":{"enum":["actor","service"]}}}}} as const satisfies JSONSchema;

export const factoryInputRequestSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/input_request.schema.json","title":"InputRequest","description":"Retry-safe durable input command. Block semantics remain transport-neutral and are validated by the receiving runtime. metadata is optional client-supplied app-defined fields; principal is optional and only ever Factory-stamped.","type":"object","additionalProperties":false,"required":["version","command_id","session_id","blocks"],"properties":{"version":{"const":1},"command_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"blocks":{"type":"array","minItems":1,"items":{"type":"object"}},"metadata":{"$ref":"#/$defs/metadata"},"principal":{"$ref":"#/$defs/principal"}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."},"metadata":{"type":"object","description":"Client-supplied app-defined string fields. Core also enforces: 1 to 16 fields; keys match ^[a-z][a-z0-9_]{0,63}$ and do not begin with looprig; values are at most 1024 bytes of UTF-8 with no C0 control other than tab and newline; the canonical encoding of the object is at most 4096 bytes.","not":{"const":{}},"additionalProperties":{"type":"string"}},"principal":{"type":"object","description":"The verified sender a Factory stamped after credential verification. Never client-supplied: a Factory refuses a request that carries it.","additionalProperties":false,"required":["tenant","subject","kind"],"properties":{"tenant":{"$ref":"#/$defs/id"},"subject":{"$ref":"#/$defs/id"},"kind":{"enum":["actor","service"]}}}}} as const satisfies JSONSchema;

export const factoryInterruptRequestSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/interrupt_request.schema.json","title":"InterruptRequest","description":"Retry-safe durable interrupt command. principal is optional and only ever Factory-stamped; metadata is never carried.","type":"object","additionalProperties":false,"required":["version","command_id","session_id"],"properties":{"version":{"const":1},"command_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"principal":{"$ref":"#/$defs/principal"}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."},"principal":{"type":"object","description":"The verified sender a Factory stamped after credential verification. Never client-supplied: a Factory refuses a request that carries it.","additionalProperties":false,"required":["tenant","subject","kind"],"properties":{"tenant":{"$ref":"#/$defs/id"},"subject":{"$ref":"#/$defs/id"},"kind":{"enum":["actor","service"]}}}}} as const satisfies JSONSchema;

export const factoryRestoreRequestSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/restore_request.schema.json","title":"RestoreRequest","description":"Explicit compatibility restore command; durable reads never imply a restore. principal is optional and only ever Factory-stamped; metadata is never carried.","type":"object","additionalProperties":false,"required":["version","command_id","session_id"],"properties":{"version":{"const":1},"command_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"principal":{"$ref":"#/$defs/principal"}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."},"principal":{"type":"object","description":"The verified sender a Factory stamped after credential verification. Never client-supplied: a Factory refuses a request that carries it.","additionalProperties":false,"required":["tenant","subject","kind"],"properties":{"tenant":{"$ref":"#/$defs/id"},"subject":{"$ref":"#/$defs/id"},"kind":{"enum":["actor","service"]}}}}} as const satisfies JSONSchema;

export const factoryGateResponseRequestSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/gate_response_request.schema.json","title":"GateResponseRequest","description":"Retry-safe private gate response. values are opaque JSON values; the request requires exactly one nonzero optimistic open version. principal is optional and only ever Factory-stamped; metadata is never carried.","type":"object","additionalProperties":false,"required":["version","command_id","session_id","gate_id","action","values"],"properties":{"version":{"const":1},"command_id":{"$ref":"#/$defs/id"},"session_id":{"$ref":"#/$defs/id"},"gate_id":{"$ref":"#/$defs/id"},"action":{"type":"string","minLength":1},"values":{"type":"object","additionalProperties":true},"expected_open_event_id":{"$ref":"#/$defs/id"},"expected_open_journal_seq":{"type":"integer","minimum":1},"principal":{"$ref":"#/$defs/principal"}},"oneOf":[{"required":["expected_open_event_id"],"not":{"required":["expected_open_journal_seq"]}},{"required":["expected_open_journal_seq"],"not":{"required":["expected_open_event_id"]}}],"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."},"principal":{"type":"object","description":"The verified sender a Factory stamped after credential verification. Never client-supplied: a Factory refuses a request that carries it.","additionalProperties":false,"required":["tenant","subject","kind"],"properties":{"tenant":{"$ref":"#/$defs/id"},"subject":{"$ref":"#/$defs/id"},"kind":{"enum":["actor","service"]}}}}} as const satisfies JSONSchema;

export const factoryPrincipalSchema = {"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://looprig.dev/sessionwire/v1/principal.schema.json","title":"Principal","description":"The verified sender of a command as a Factory established it. Never client-supplied; holds only verified facts (display names are resolved by the application from subject). Carried by every command request as the optional principal member.","type":"object","additionalProperties":false,"required":["tenant","subject","kind"],"properties":{"tenant":{"$ref":"#/$defs/id"},"subject":{"$ref":"#/$defs/id"},"kind":{"enum":["actor","service"]}},"$defs":{"id":{"type":"string","minLength":1,"description":"Opaque UTF-8 identity; Core enforces the 256-byte limit."}}} as const satisfies JSONSchema;

export const factorySchemas = {
  "create_request": factoryCreateRequestSchema,
  "input_request": factoryInputRequestSchema,
  "interrupt_request": factoryInterruptRequestSchema,
  "restore_request": factoryRestoreRequestSchema,
  "gate_response_request": factoryGateResponseRequestSchema,
  "principal": factoryPrincipalSchema,
  "agent_capability_summary": factoryAgentCapabilitySummarySchema,
  "department_capability_summary": factoryDepartmentCapabilitySummarySchema,
  "recent_session_page": factoryRecentSessionPageSchema,
  "session_status": factorySessionStatusSchema,
  "public_journal_page": factoryPublicJournalPageSchema,
  "public_gate_page": factoryPublicGatePageSchema,
  "object_metadata": factoryObjectMetadataSchema,
  "enduring_publication": factoryEnduringPublicationSchema,
  "ephemeral_publication": factoryEphemeralPublicationSchema,
  "journal_tip": factoryJournalTipSchema,
  "session_reset": factorySessionResetSchema,
  "version_negotiation_request": factoryVersionNegotiationRequestSchema,
  "version_negotiation_response": factoryVersionNegotiationResponseSchema,
  "command_status": factoryCommandStatusSchema,
  "error_envelope": factoryErrorEnvelopeSchema,
} as const;
